Fixes for C++20 errors when compiling with MSVC.
Worked around "error C2064: term does not evaluate to a function
taking 0 arguments" that was produced when compiling code that
included t_generator.h

Patched TFDTransport.cpp to replace std::uncaught_exception(),
which was removed in C++20, with a call to std::uncaught_exceptions().